"""empty message

Revision ID: 788d22f93a1e
Revises: f9d7a9142b82
Create Date: 2025-11-24 15:32:21.518134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '788d22f93a1e'
down_revision = 'f9d7a9142b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('whatsapp_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('business_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('open_duration', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('year_of_establishment', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('rater_no', sa.Integer(), nullable=True))
        batch_op.drop_column('gst_number')
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('gst_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('rater_no')
        batch_op.drop_column('rating')
        batch_op.drop_column('year_of_establishment')
        batch_op.drop_column('payment_type')
        batch_op.drop_column('open_duration')
        batch_op.drop_column('business_name')
        batch_op.drop_column('email')
        batch_op.drop_column('whatsapp_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
